#!/bin/bash
# shellcheck disable=SC1090
rules="$1"
# Read the keys
mapfile -t keys < <(awk -F= '{print $1}' < "$rules")
# Read the values
source "$rules"

for key in "${keys[@]}"
do
  sed_args+=";s@\@${key}\@@${!key}@g"
done

exec sed "$sed_args"
